name:  Recordbase CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install tools
        run: |
          sudo apt-get update
          sudo apt-get install --assume-yes curl make unzip

      - name: Install protoc
        run: sudo bash .github/scripts/install-protoc.sh 3.20.3

      - name: Verify protoc
        run: protoc --version

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.17'

      - name: Install dependencies
        run: make deps

      - name: Build
        run: make
